name: shopify-cli-next

up:
  - node:
      yarn: true
      version: v16.13.2
      packages:
        - ./
        - ./docs

env:
  SHOPIFY_CONFIG: debug
  SHOPIFY_PARTNERS_API_ENV: production
  SHOPIFY_ADMIN_API_ENV: production
  SHOPIFY_STOREFRONT_RENDERER_API_ENV: production
  SHOPIFY_IDENTITY_API_ENV: production

open:
  app: http://localhost:3000

commands:
  shopify:
    desc: 'Runs the Shopify CLI'
    run: packages/cli/bin/shopify-dev.js
  create-app:
    desc: 'Runs the create-app CLI'
    run: packages/create-app/bin/create-app-dev.js
  test:
    desc: 'Runs the tests'
    run: yarn run test
  build:
    desc: 'Build the project'
    run: yarn run build
  lint:
    desc: 'Lint the project'
    run: yarn run lint
  lint:fix:
    desc: 'Fix the lint issues in the project'
    run: yarn run lint:fix
  tsc:
    desc: 'Type-check the project'
    run: yarn run tsc
  server:
    depends-railgun: true
    desc: Run docusaurus documentation local server
    run: yarn --cwd docs run start --no-open
  docs:
    desc: 'Commands to interact with the documentation website.'
    subcommands:
      server:
        desc: Run docusaurus documentation local server
        run: yarn --cwd docs run start --no-open

      build:
        desc: build and serve the static website
        run: |
          yarn --cwd docs run build
          yarn --cwd docs run serve
