blank_issues_enabled: true
contact_links:
  - name: Shopify Partners Community
    url: https://www.shopify.com/partners/community#conversation
    about: Connect with Shopify and other Shopify Partners through our online communities!
