blank_issues_enabled: true
contact_links:
  - name: Shopify Partners Community 🙌
    url: https://www.shopify.com/partners/community#conversation
    about: Connect with Shopify and other Shopify Partners through our online communities!
  - name: Ruby CLI issues 📝
    url: https://www.github.com/Shopify/shopify-cli/issues/new/choose
    about: Are you using our previous Ruby CLI? Please create an issue there instead.
