name: cli

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: cli-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build
        working-directory: packages/cli
        run: yarn run build
  test:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Test
        working-directory: packages/cli
        run: yarn run test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        working-directory: packages/cli
        run: yarn run lint
  type-check:
    name: Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Type-check
        working-directory: packages/cli
        run: yarn run tsc
