# This file stores configurations for your Shopify app extension.

name = "{{name}}"
extensionType = "{{extensionType}}"

# [[metafield]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafield]]
# namespace = "my-namespace"
# key = "my-key-2"
