# This file stores configurations for your Shopify app UI extension.

name = "{{name}}"
type = "{{extensionType}}"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"
