name: "Download and publish benchmark"
description: "Downloads benchmark coverage stats from the base branch, publishes a comment with a summary"
inputs:
  base-branch-name:
    required: true
    description: "Name of the branch to compare coverage with"
runs:
  using: "composite"
  steps:
    # Strips forward slashes and dots as not supported by artifact commands
    - name: Clean base ref name
      shell: bash
      env:
          SAFE_BASE_REF_NAME: "${{ inputs.base-branch-name }}"
      run: |
        SAFE_BASE_REF_NAME=${{ env.SAFE_BASE_REF_NAME }}
        SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME//[\/.]/}
        echo SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME} >> $GITHUB_ENV
    - name: Download artifact
      continue-on-error: true
      id: download-artifact
      # We use this action and not Github's default, due to https://github.com/actions/download-artifact/issues/3
      uses: dawidd6/action-download-artifact@v2.24.2
      with:
        workflow: shopify-cli.yml
        workflow_conclusion: success
        branch: ${{ inputs.base-branch-name }}
        name: ${{ env.SAFE_BASE_REF_NAME }}--benchmark
        if_no_artifact_found: ignore
    - name: Generate report
      id: benchmark
      run: node workspace/src/generate-benchmark-report.js
      shell: bash
    - uses: marocchino/sticky-pull-request-comment@v2.3.1
      with:
        header: Benchmark
        message: ${{ steps.benchmark.outputs.report }}
