name: benchmark

on:
  pull_request:
    paths-ignore:
      - '**.md'

env:
  DEBUG: "1"
  SHOPIFY_CLI_ENV: development
  SHOPIFY_CONFIG: debug
  YARN_VERSION: "1.22.19"
  PNPM_VERSION: "7.18.1"

jobs:
  benchmark:
    name: Benchmark ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'push' }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: ['18.7.0']
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Setup deps
        uses: ./.github/actions/setup-cli-deps
        with:
          node-version: ${{ matrix.node }}
      - name: Build
        run: pnpm nx run-many --all --skip-nx-cache --target=build --exclude=features
      - name: Benchmark
        working-directory: workspace
        run: pnpm nx run benchmark
