name: shopify-cli

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: shopify-cli-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1
  YARN_VERSION: "1.22.18"
  RUBY_VERSION: "3.1.2"

jobs:
  main:
    name: Node ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    strategy:
      matrix:
        node: ['14', '16', '17', '18']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Set Git configuration
        run: |
          git config --global user.email "development-lifecycle@shopify.com"
          git config --global user.name "Development Lifecycle"
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Set Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install Playwright dependencies
        run: npx playwright install-deps chromium
      - name: Install yarn
        run: npm install --global yarn@${{ env.YARN_VERSION }}
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Build
        run: npx nx affected --target=build --skip-nx-cache
      - name: Test
        run: npx nx affected --target=test --skip-nx-cache
      - name: Lint
        run: npx nx affected --target=lint --skip-nx-cache
      - name: Type-check
        run: npx nx affected --target=tsc --skip-nx-cache
  pr:
    name: Node ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        node: ['14', '16', '17', '18']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Set Git configuration
        run: |
          git config --global user.email "development-lifecycle@shopify.com"
          git config --global user.name "Development Lifecycle"
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Set Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install Playwright dependencies
        run: npx playwright install-deps chromium
      - name: Install yarn
        run: npm install --global yarn@${{ env.YARN_VERSION }}
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Build
        run: npx nx affected --target=build --skip-nx-cache
      - name: Test
        run: npx nx affected --target=test --skip-nx-cache
      - name: Lint
        run: npx nx affected --target=lint --skip-nx-cache
      - name: Type-check
        run: npx nx affected --target=tsc --skip-nx-cache
