name: shopify-cli

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: shopify-cli-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Node ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    strategy:
      matrix:
        node: ['14.13.1', '16', '17']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --ignore-engines && yarn install --ignore-engines --cwd docs
      - name: Build
        run: npx nx affected --target=build --parallel=3
      - name: Test
        run: npx nx affected --target=test --parallel=3
      - name: Lint
        run: npx nx affected --target=lint --parallel=3
      - name: Type-check
        run: npx nx affected --target=tsc --parallel=3
  pr:
    name: Node ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        node: ['14.13.1', '16', '17']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --ignore-engines && yarn install --ignore-engines --cwd docs
      - name: Build
        run: npx nx affected --target=build --parallel=3
      - name: Test
        run: npx nx affected --target=test --parallel=3
      - name: Lint
        run: npx nx affected --target=lint --parallel=3
      - name: Type-check
        run: npx nx affected --target=tsc --parallel=3
