name: shopify-cli

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: shopify-cli-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.package }} with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
        package: ['support', 'cli', 'core', 'create-shopify-app', 'app']
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build
        working-directory: packages/${{ matrix.package }}
        run: yarn run build
  test:
    name: Test ${{ matrix.package }} with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
        package: ['support', 'cli', 'core', 'create-shopify-app', 'app']
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Test
        working-directory: packages/${{ matrix.package }}
        run: yarn run test
  lint:
    name: Lint ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['support', 'cli', 'core', 'create-shopify-app', 'app']
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        working-directory: packages/${{ matrix.package }}
        run: yarn run lint
  type-check:
    name: Type-check ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['support', 'cli', 'core', 'create-shopify-app', 'app']
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Type-check
        working-directory: packages/${{ matrix.package }}
        run: yarn run tsc
